WITH ATTEMPTS AS (
    SELECT 
        fp.SUBJECT_ID,
        e.STUDENT_ID,
        COUNT(*) AS ATTEMPTS
    FROM 
        F_ACADEMIC_PERFORMANCE fp
    INNER JOIN 
        D_ENROLLMENTS e 
    ON 
        fp.ENROLLMENT_ID = e.ENROLLMENT_ID
    GROUP BY 
        fp.SUBJECT_ID, e.STUDENT_ID
),
FIRST_ENROLLMENT_YEAR AS (
    SELECT 
        STUDENT_ID,
        MIN(ay.ACADEMIC_YEAR) AS FIRST_ENROLLMENT_YEAR
    FROM 
        D_ENROLLMENTS e
    INNER JOIN
        D_ACADEMIC_YEAR ay
    ON 
        e.ACADEMIC_YEAR_ID = ay.ACADEMIC_YEAR_ID
    GROUP BY 
        STUDENT_ID
)
SELECT 
    ds.STUDENT_ID,
    e.ENROLLMENT_MODE,
    sbs.SUBJECT_NAME,
    sbs.SEMESTER AS SUBJECT_SEMESTER,
    sbs.YEAR AS SUBJECT_YEAR,
    e.ENROLLMENT_ID,
    ay.ACADEMIC_YEAR AS ENROLLMENT_ACADEMIC_YEAR,
    fe.FIRST_ENROLLMENT_YEAR + (sbs.YEAR - 1) AS EXPECT_SUBJECT_COMPLETION_YEAR,
    a.ATTEMPTS,
    fp.FINAL_GRADE,
    fp.STATUS
FROM 
    F_ACADEMIC_PERFORMANCE fp
INNER JOIN 
    D_ENROLLMENTS e 
ON 
    fp.ENROLLMENT_ID = e.ENROLLMENT_ID
INNER JOIN
    D_ACADEMIC_YEAR ay
ON
    e.ACADEMIC_YEAR_ID = ay.ACADEMIC_YEAR_ID
INNER JOIN 
    D_STUDENTS ds
ON 
    ds.STUDENT_ID = e.STUDENT_ID
INNER JOIN 
    D_SUBJECTS sbs
ON 
    sbs.SUBJECT_ID = fp.SUBJECT_ID
INNER JOIN 
    ATTEMPTS a
ON 
    a.SUBJECT_ID = fp.SUBJECT_ID
    AND a.STUDENT_ID = ds.STUDENT_ID
INNER JOIN 
    FIRST_ENROLLMENT_YEAR fe
ON 
    fe.STUDENT_ID = ds.STUDENT_ID
WHERE 
    ds.STUDENT_ID = 10003
ORDER BY 
    e.ENROLLMENT_ID, sbs.SEMESTER;
